export type SeedProduct = {
  nombre: string;
  presentacion: string;
  categoria: string;
  precioVenta: string; // precio de venta al público (de la lista)
};

/**
 * Catálogo real del comercio.
 * `precioVenta` = precio de la lista (lo que paga el cliente).
 * El `costo` se carga después desde el módulo de Productos; mientras tanto
 * queda nulo y el margen real se calcula solo cuando lo completes.
 */
export const catalogo: SeedProduct[] = [
  // ---------- Medicamentos ----------
  { nombre: "ACTRON 400 R.A", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "3520.00" },
  { nombre: "ACTRON 600", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "8380.00" },
  { nombre: "ACTRON MUJER", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "3550.00" },
  { nombre: "ALIKAL", presentacion: "X 1", categoria: "Medicamentos", precioVenta: "820.00" },
  { nombre: "ALIKAL LIMON", presentacion: "X 1", categoria: "Medicamentos", precioVenta: "820.00" },
  { nombre: "ALIKAL NARANJA", presentacion: "X 1", categoria: "Medicamentos", precioVenta: "820.00" },
  { nombre: "Amoxicilina FABOP", presentacion: "X 8", categoria: "Medicamentos", precioVenta: "1850.00" },
  { nombre: "ANAFLEX PLUS", presentacion: "X 9", categoria: "Medicamentos", precioVenta: "3370.00" },
  { nombre: "ASPIRINETAS", presentacion: "X 14", categoria: "Medicamentos", precioVenta: "990.00" },
  { nombre: "BAYA C", presentacion: "X 1", categoria: "Medicamentos", precioVenta: "1190.00" },
  { nombre: "BAYA C Caliente", presentacion: "X 1", categoria: "Medicamentos", precioVenta: "1550.00" },
  { nombre: "BAYASPIRINA", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "1960.00" },
  { nombre: "BAYASPIRINA FORTE", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "2540.00" },
  { nombre: "BUSCAPINA COMPUESTA", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "9110.00" },
  { nombre: "BUSCAPINA DUO", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "8530.00" },
  { nombre: "BUSCAPINA FEM", presentacion: "X 6", categoria: "Medicamentos", precioVenta: "3800.00" },
  { nombre: "BUSCAPINA PERLAS", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "6340.00" },
  { nombre: "CAFIASPIRINA X 30", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "2300.00" },
  { nombre: "CAFIASPIRINA PLUS", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "2880.00" },
  { nombre: "CARBON", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "630.00" },
  { nombre: "DICLOFENAC 75 mg", presentacion: "X 15", categoria: "Medicamentos", precioVenta: "760.00" },
  { nombre: "DICLO + PRIDINOL", presentacion: "X 15", categoria: "Medicamentos", precioVenta: "1120.00" },
  { nombre: "DORIXINA", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "3070.00" },
  { nombre: "FEEN A MINT", presentacion: "X 6", categoria: "Medicamentos", precioVenta: "4470.00" },
  { nombre: "GENIOL 500mg", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "1630.00" },
  { nombre: "GENIOL 1Gr", presentacion: "X 8", categoria: "Medicamentos", precioVenta: "2100.00" },
  { nombre: "GENIOL PLUS Rap. Acc.", presentacion: "X 6", categoria: "Medicamentos", precioVenta: "2990.00" },
  { nombre: "HEPATALGINA", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "5090.00" },
  { nombre: "HEPATALGINA GOTAS", presentacion: "X 1", categoria: "Medicamentos", precioVenta: "7320.00" },
  { nombre: "IBUEVANOL FORTE", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "3070.00" },
  { nombre: "IBUEVANOL MAX", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "3720.00" },
  { nombre: "IBUEVANOL PLUS", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "2530.00" },
  { nombre: "IBUEVANOL RAP. ACC.", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "2310.00" },
  { nombre: "IBUPIRAC", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "2910.00" },
  { nombre: "IBUPIRAC 600", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "6760.00" },
  { nombre: "IBUPIRETA JR.", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "4980.00" },
  { nombre: "IBUPIRAC MIGRA", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "7220.00" },
  { nombre: "IBUPROFENO 400 mg. TRB", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "690.00" },
  { nombre: "IBUPROFENO 600 mg. TRB", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "980.00" },
  { nombre: "KETEROLAC", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "730.00" },
  { nombre: "KETEROLAC SUBLINGUAL", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "650.00" },
  { nombre: "LORATADINA", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "630.00" },
  { nombre: "MEJORAL P NIÑOS", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "3150.00" },
  { nombre: "MIGRAL COMP.", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "4810.00" },
  { nombre: "MYLANTA", presentacion: "X 8", categoria: "Medicamentos", precioVenta: "3810.00" },
  { nombre: "NEXT GRIPE", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "3830.00" },
  { nombre: "NOVALGINA", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "7660.00" },
  { nombre: "OMEPRAZOL", presentacion: "X 14", categoria: "Medicamentos", precioVenta: "1010.00" },
  { nombre: "PARACETAMOL", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "700.00" },
  { nombre: "PARACETAMOL 1GR", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "1360.00" },
  { nombre: "PONSTIL FORTE", presentacion: "X 5", categoria: "Medicamentos", precioVenta: "2270.00" },
  { nombre: "QURA PLUS", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "4730.00" },
  { nombre: "REFRIANEX COMPUESTO", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "4680.00" },
  { nombre: "REFENAX GOTAS NASALES", presentacion: "X 1", categoria: "Medicamentos", precioVenta: "6370.00" },
  { nombre: "RENNIE", presentacion: "X 8", categoria: "Medicamentos", precioVenta: "5270.00" },
  { nombre: "RESAQUIT", presentacion: "X 4", categoria: "Medicamentos", precioVenta: "2680.00" },
  { nombre: "SERTAL CTO", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "8350.00" },
  { nombre: "SERTAL PERLAS", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "5820.00" },
  { nombre: "TAFIROL", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "2590.00" },
  { nombre: "TAFIROL DUO", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "4390.00" },
  { nombre: "TAFIROL FORTE", presentacion: "X 8", categoria: "Medicamentos", precioVenta: "3060.00" },
  { nombre: "TAFIROL 1 G", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "2410.00" },
  { nombre: "TAFIROL MIGRA", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "4900.00" },
  { nombre: "TAFIROL PLUS", presentacion: "X 8", categoria: "Medicamentos", precioVenta: "3410.00" },
  { nombre: "TETRALGIN", presentacion: "X 10", categoria: "Medicamentos", precioVenta: "4970.00" },
  { nombre: "TE VENT3", presentacion: "X 1", categoria: "Medicamentos", precioVenta: "1250.00" },
  { nombre: "TE VENT3 PLUS", presentacion: "X 1", categoria: "Medicamentos", precioVenta: "1450.00" },
  { nombre: "TE VICK", presentacion: "X 1", categoria: "Medicamentos", precioVenta: "2770.00" },
  { nombre: "TE VICK FORTE", presentacion: "X 1", categoria: "Medicamentos", precioVenta: "2860.00" },
  { nombre: "TE NEXT FORTE", presentacion: "X 1", categoria: "Medicamentos", precioVenta: "1860.00" },
  { nombre: "UVASAL", presentacion: "X 1", categoria: "Medicamentos", precioVenta: "510.00" },
  { nombre: "UVASAL LIM", presentacion: "X 1", categoria: "Medicamentos", precioVenta: "510.00" },
  { nombre: "UVASAL NJA", presentacion: "X 1", categoria: "Medicamentos", precioVenta: "510.00" },

  // ---------- Higiene y botiquín ----------
  { nombre: "AGUA OXIGENADA 10V", presentacion: "X 5", categoria: "Higiene y botiquín", precioVenta: "520.00" },
  { nombre: "ALCOHOL 250cc", presentacion: "X 1", categoria: "Higiene y botiquín", precioVenta: "1100.00" },
  { nombre: "AZUFRE", presentacion: "X 1", categoria: "Higiene y botiquín", precioVenta: "700.00" },
  { nombre: "BICARBONATO", presentacion: "X 1", categoria: "Higiene y botiquín", precioVenta: "350.00" },
  { nombre: "CURITAS", presentacion: "X 1", categoria: "Higiene y botiquín", precioVenta: "1300.00" },
  { nombre: "BX7", presentacion: "X 1", categoria: "Higiene y botiquín", precioVenta: "740.00" },
  { nombre: "GASAS", presentacion: "X 1", categoria: "Higiene y botiquín", precioVenta: "2800.00" },
  { nombre: "MANTECA DE CACAO", presentacion: "X 1", categoria: "Higiene y botiquín", precioVenta: "920.00" },
  { nombre: "PAÑUELOS DESCARTABLES 6X10", presentacion: "X 1", categoria: "Higiene y botiquín", precioVenta: "1020.00" },
  { nombre: "PAÑUELOS ELITE 6X10", presentacion: "X 1", categoria: "Higiene y botiquín", precioVenta: "1500.00" },
  { nombre: "SUERO FISIOLOGICO", presentacion: "X 1", categoria: "Higiene y botiquín", precioVenta: "1580.00" },
  { nombre: "TARROS", presentacion: "X 1", categoria: "Higiene y botiquín", precioVenta: "700.00" },
];
